//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnoTent.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания ООО &quot;Техно Тент&quot; выполняет полный комплекс работ по  изготовлению автомобильных тентов, крыш, штор из качественного материала ПВХ с использованием фурнитуры высокого качества, возможно нанесение рекламы. Также производит обслуживание и ремонт тентов для автомобилей различных моделей и марок. Помимо этого, мы производим переделку автотентов,  замену отдельно боковин, крыши или торца и изменение высоты и длины тентов. Возможен как капитальный ремонт тента, так и устранение различных порезов, замена л [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string about_about {
            get {
                return ResourceManager.GetString("about_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фактический адрес.
        /// </summary>
        public static string about_org_address1 {
            get {
                return ResourceManager.GetString("about_org_address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г.Киев, Новоконстантиновская 4а | г.Константиновка, ул. Мирошниченко 7.
        /// </summary>
        public static string about_org_address2 {
            get {
                return ResourceManager.GetString("about_org_address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование организации.
        /// </summary>
        public static string about_org_name1 {
            get {
                return ResourceManager.GetString("about_org_name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общество с ограниченной ответственностью &quot;Техно Тент&quot;.
        /// </summary>
        public static string about_org_name2 {
            get {
                return ResourceManager.GetString("about_org_name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реквизиты.
        /// </summary>
        public static string about_org_requisites {
            get {
                return ResourceManager.GetString("about_org_requisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Банковские реквизиты.
        /// </summary>
        public static string about_org_requisites1 {
            get {
                return ResourceManager.GetString("about_org_requisites1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Банк ПАТ &quot;ПРИВАТБАНК&quot;.
        /// </summary>
        public static string about_org_requisites2 {
            get {
                return ResourceManager.GetString("about_org_requisites2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на П/р.
        /// </summary>
        public static string about_org_requisites3 {
            get {
                return ResourceManager.GetString("about_org_requisites3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МФО.
        /// </summary>
        public static string about_org_requisites4 {
            get {
                return ResourceManager.GetString("about_org_requisites4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЕГРПОУ.
        /// </summary>
        public static string about_org_requisites5 {
            get {
                return ResourceManager.GetString("about_org_requisites5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИНН.
        /// </summary>
        public static string about_org_requisites6 {
            get {
                return ResourceManager.GetString("about_org_requisites6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сайт.
        /// </summary>
        public static string about_org_requisites7 {
            get {
                return ResourceManager.GetString("about_org_requisites7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон организации, e-mail.
        /// </summary>
        public static string about_org_tel {
            get {
                return ResourceManager.GetString("about_org_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продажа ПВХ.
        /// </summary>
        public static string about_org_tel1 {
            get {
                return ResourceManager.GetString("about_org_tel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Швейное производство.
        /// </summary>
        public static string about_org_tel2 {
            get {
                return ResourceManager.GetString("about_org_tel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер ПВХ.
        /// </summary>
        public static string about_org_tel3 {
            get {
                return ResourceManager.GetString("about_org_tel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производство, г.Константиновка.
        /// </summary>
        public static string about_org_tel4 {
            get {
                return ResourceManager.GetString("about_org_tel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер Viber.
        /// </summary>
        public static string about_org_tel5 {
            get {
                return ResourceManager.GetString("about_org_tel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гл. бухгалтер.
        /// </summary>
        public static string about_org_tel6 {
            get {
                return ResourceManager.GetString("about_org_tel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О нас.
        /// </summary>
        public static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите Email.
        /// </summary>
        public static string auth_email_err {
            get {
                return ResourceManager.GetString("auth_email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string auth_enter {
            get {
                return ResourceManager.GetString("auth_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваше имя.
        /// </summary>
        public static string auth_name {
            get {
                return ResourceManager.GetString("auth_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string auth_name_err {
            get {
                return ResourceManager.GetString("auth_name_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string auth_pass {
            get {
                return ResourceManager.GetString("auth_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string auth_pass_err {
            get {
                return ResourceManager.GetString("auth_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string auth_pass_err1 {
            get {
                return ResourceManager.GetString("auth_pass_err1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Придумайте пароль.
        /// </summary>
        public static string auth_pass1 {
            get {
                return ResourceManager.GetString("auth_pass1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите пароль.
        /// </summary>
        public static string auth_repass {
            get {
                return ResourceManager.GetString("auth_repass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не совпадают.
        /// </summary>
        public static string auth_repass_err {
            get {
                return ResourceManager.GetString("auth_repass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string auth_signin {
            get {
                return ResourceManager.GetString("auth_signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string auth_signup {
            get {
                return ResourceManager.GetString("auth_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        public static string auth_signup1 {
            get {
                return ResourceManager.GetString("auth_signup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не можете войти?.
        /// </summary>
        public static string auth_trouble {
            get {
                return ResourceManager.GetString("auth_trouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оформить заказ.
        /// </summary>
        public static string cart_checkout {
            get {
                return ResourceManager.GetString("cart_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукт.
        /// </summary>
        public static string cart_col1 {
            get {
                return ResourceManager.GetString("cart_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string cart_col2 {
            get {
                return ResourceManager.GetString("cart_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string cart_col3 {
            get {
                return ResourceManager.GetString("cart_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость.
        /// </summary>
        public static string cart_col4 {
            get {
                return ResourceManager.GetString("cart_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корзина пуста.
        /// </summary>
        public static string cart_empty {
            get {
                return ResourceManager.GetString("cart_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая стоимость заказа.
        /// </summary>
        public static string cart_total_price {
            get {
                return ResourceManager.GetString("cart_total_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ул. Новоконстантиновская, 4 а.
        /// </summary>
        public static string contacts_address {
            get {
                return ResourceManager.GetString("contacts_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ул. Мирошниченко, 7.
        /// </summary>
        public static string contacts_address1 {
            get {
                return ResourceManager.GetString("contacts_address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не смогли дозвониться.
        /// </summary>
        public static string contacts_backCall1 {
            get {
                return ResourceManager.GetString("contacts_backCall1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закажите звонок.
        /// </summary>
        public static string contacts_backCall2 {
            get {
                return ResourceManager.GetString("contacts_backCall2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Константиновка.
        /// </summary>
        public static string contacts_city {
            get {
                return ResourceManager.GetString("contacts_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Киев.
        /// </summary>
        public static string contacts_city2 {
            get {
                return ResourceManager.GetString("contacts_city2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Украина.
        /// </summary>
        public static string contacts_country {
            get {
                return ResourceManager.GetString("contacts_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пн-Пт 09:00-18:00.
        /// </summary>
        public static string contacts_dates {
            get {
                return ResourceManager.GetString("contacts_dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обратная связь.
        /// </summary>
        public static string contacts_feedback {
            get {
                return ResourceManager.GetString("contacts_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректный адрес электронной почты.
        /// </summary>
        public static string contacts_form_email {
            get {
                return ResourceManager.GetString("contacts_form_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите сообщение.
        /// </summary>
        public static string contacts_form_msg {
            get {
                return ResourceManager.GetString("contacts_form_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string contacts_form_name {
            get {
                return ResourceManager.GetString("contacts_form_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить сообщение.
        /// </summary>
        public static string contacts_form_send {
            get {
                return ResourceManager.GetString("contacts_form_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производство.
        /// </summary>
        public static string contacts_manuf {
            get {
                return ResourceManager.GetString("contacts_manuf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продажа ПВХ.
        /// </summary>
        public static string contacts_tel1 {
            get {
                return ResourceManager.GetString("contacts_tel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производство.
        /// </summary>
        public static string contacts_tel2 {
            get {
                return ResourceManager.GetString("contacts_tel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тентовая и запорная фурнитура.
        /// </summary>
        public static string contacts_tel3 {
            get {
                return ResourceManager.GetString("contacts_tel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер Viber.
        /// </summary>
        public static string contacts_tel4 {
            get {
                return ResourceManager.GetString("contacts_tel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мой кабинет.
        /// </summary>
        public static string edit_acc {
            get {
                return ResourceManager.GetString("edit_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string edit_cancel {
            get {
                return ResourceManager.GetString("edit_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронная почтa.
        /// </summary>
        public static string edit_email {
            get {
                return ResourceManager.GetString("edit_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите электронную почту.
        /// </summary>
        public static string edit_email_err {
            get {
                return ResourceManager.GetString("edit_email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string edit_name {
            get {
                return ResourceManager.GetString("edit_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя и фамилию.
        /// </summary>
        public static string edit_name_err {
            get {
                return ResourceManager.GetString("edit_name_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Придумайте новый пароль.
        /// </summary>
        public static string edit_newpass {
            get {
                return ResourceManager.GetString("edit_newpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите  новый пароль.
        /// </summary>
        public static string edit_newpass_err {
            get {
                return ResourceManager.GetString("edit_newpass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль еще раз.
        /// </summary>
        public static string edit_newpass_more {
            get {
                return ResourceManager.GetString("edit_newpass_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите новый пароль еще раз.
        /// </summary>
        public static string edit_newpass_more_err {
            get {
                return ResourceManager.GetString("edit_newpass_more_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История заказов.
        /// </summary>
        public static string edit_order_history {
            get {
                return ResourceManager.GetString("edit_order_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string edit_order_logout {
            get {
                return ResourceManager.GetString("edit_order_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите старый пароль.
        /// </summary>
        public static string edit_pass {
            get {
                return ResourceManager.GetString("edit_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string edit_pass_err {
            get {
                return ResourceManager.GetString("edit_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Личные данные.
        /// </summary>
        public static string edit_private {
            get {
                return ResourceManager.GetString("edit_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string edit_submit {
            get {
                return ResourceManager.GetString("edit_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string edit_tel {
            get {
                return ResourceManager.GetString("edit_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на почему с нами выгодно сотрудничать?.
        /// </summary>
        public static string home_advantage_title {
            get {
                return ResourceManager.GetString("home_advantage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реализуем любой объем продукции.
        /// </summary>
        public static string home_advantage1 {
            get {
                return ResourceManager.GetString("home_advantage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объем продукции.
        /// </summary>
        public static string home_advantage1_alt {
            get {
                return ResourceManager.GetString("home_advantage1_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прямые поставки с завода производителя.
        /// </summary>
        public static string home_advantage2 {
            get {
                return ResourceManager.GetString("home_advantage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставки с завода.
        /// </summary>
        public static string home_advantage2_alt {
            get {
                return ResourceManager.GetString("home_advantage2_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Качество гарантированно ISO 9001:2000.
        /// </summary>
        public static string home_advantage3 {
            get {
                return ResourceManager.GetString("home_advantage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Качество гарантированно.
        /// </summary>
        public static string home_advantage3_alt {
            get {
                return ResourceManager.GetString("home_advantage3_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широкий ассортимент.
        /// </summary>
        public static string home_advantage4 {
            get {
                return ResourceManager.GetString("home_advantage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демонтаж, монтаж-оперативно, аккуратно.
        /// </summary>
        public static string home_advantage5 {
            get {
                return ResourceManager.GetString("home_advantage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демонтаж, монтаж.
        /// </summary>
        public static string home_advantage5_alt {
            get {
                return ResourceManager.GetString("home_advantage5_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позвоните нам или оставьте свой номер телефона, и мы поможем.
        /// </summary>
        public static string home_feedback_desc {
            get {
                return ResourceManager.GetString("home_feedback_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вам выбрать то, что нужно.
        /// </summary>
        public static string home_feedback_desc2 {
            get {
                return ResourceManager.GetString("home_feedback_desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на оставить заявку.
        /// </summary>
        public static string home_feedback_submit {
            get {
                return ResourceManager.GetString("home_feedback_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отдел продаж.
        /// </summary>
        public static string home_feedback_tel11 {
            get {
                return ResourceManager.GetString("home_feedback_tel11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производство.
        /// </summary>
        public static string home_feedback_tel2 {
            get {
                return ResourceManager.GetString("home_feedback_tel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужно что-то.
        /// </summary>
        public static string home_feedback1 {
            get {
                return ResourceManager.GetString("home_feedback1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на особенное.
        /// </summary>
        public static string home_feedback2 {
            get {
                return ResourceManager.GetString("home_feedback2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статьи и новости.
        /// </summary>
        public static string home_news {
            get {
                return ResourceManager.GetString("home_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Читать все статьи.
        /// </summary>
        public static string home_news_all {
            get {
                return ResourceManager.GetString("home_news_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наши партнеры.
        /// </summary>
        public static string home_partners {
            get {
                return ResourceManager.GetString("home_partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основные виды продукции.
        /// </summary>
        public static string home_production_title {
            get {
                return ResourceManager.GetString("home_production_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тентовые ткани ПВХ.
        /// </summary>
        public static string home_production1 {
            get {
                return ResourceManager.GetString("home_production1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тентовые ткани.
        /// </summary>
        public static string home_production1_alt {
            get {
                return ResourceManager.GetString("home_production1_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тенты.
        /// </summary>
        public static string home_production2 {
            get {
                return ResourceManager.GetString("home_production2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пошив.
        /// </summary>
        public static string home_production3 {
            get {
                return ResourceManager.GetString("home_production3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каркасные сооружения.
        /// </summary>
        public static string home_production4 {
            get {
                return ResourceManager.GetString("home_production4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высотные работы.
        /// </summary>
        public static string home_production5 {
            get {
                return ResourceManager.GetString("home_production5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фурнитура.
        /// </summary>
        public static string home_production6 {
            get {
                return ResourceManager.GetString("home_production6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акции.
        /// </summary>
        public static string home_stocks {
            get {
                return ResourceManager.GetString("home_stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Читать все акции.
        /// </summary>
        public static string home_stocks_all {
            get {
                return ResourceManager.GetString("home_stocks_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Характеристики.
        /// </summary>
        public static string item_about {
            get {
                return ResourceManager.GetString("item_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить в корзину.
        /// </summary>
        public static string item_add_to_cart {
            get {
                return ResourceManager.GetString("item_add_to_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочность при адгезии.
        /// </summary>
        public static string item_adhesionStrength {
            get {
                return ResourceManager.GetString("item_adhesionStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочность на розрыв.
        /// </summary>
        public static string item_breakingStrength {
            get {
                return ResourceManager.GetString("item_breakingStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код товара.
        /// </summary>
        public static string item_code {
            get {
                return ResourceManager.GetString("item_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет.
        /// </summary>
        public static string item_color {
            get {
                return ResourceManager.GetString("item_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string item_count {
            get {
                return ResourceManager.GetString("item_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна производителя.
        /// </summary>
        public static string item_countryOfOrigin {
            get {
                return ResourceManager.GetString("item_countryOfOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Покрытие.
        /// </summary>
        public static string item_cover {
            get {
                return ResourceManager.GetString("item_cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Покрытие.
        /// </summary>
        public static string item_covering {
            get {
                return ResourceManager.GetString("item_covering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доставка.
        /// </summary>
        public static string item_delivery {
            get {
                return ResourceManager.GetString("item_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Плотность.
        /// </summary>
        public static string item_dencity {
            get {
                return ResourceManager.GetString("item_dencity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string item_description {
            get {
                return ResourceManager.GetString("item_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уменьшить.
        /// </summary>
        public static string item_down {
            get {
                return ResourceManager.GetString("item_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товара нет в наличии.
        /// </summary>
        public static string item_empty_product {
            get {
                return ResourceManager.GetString("item_empty_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Извините.
        /// </summary>
        public static string item_empty_sry {
            get {
                return ResourceManager.GetString("item_empty_sry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота.
        /// </summary>
        public static string item_height {
            get {
                return ResourceManager.GetString("item_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производитель.
        /// </summary>
        public static string item_manuf {
            get {
                return ResourceManager.GetString("item_manuf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Материал.
        /// </summary>
        public static string item_material {
            get {
                return ResourceManager.GetString("item_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оригинал.
        /// </summary>
        public static string item_original {
            get {
                return ResourceManager.GetString("item_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплата.
        /// </summary>
        public static string item_payment {
            get {
                return ResourceManager.GetString("item_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время изготовления.
        /// </summary>
        public static string item_preparationTime {
            get {
                return ResourceManager.GetString("item_preparationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string item_price {
            get {
                return ResourceManager.GetString("item_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товары и услуги.
        /// </summary>
        public static string item_route1 {
            get {
                return ResourceManager.GetString("item_route1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сезон.
        /// </summary>
        public static string item_season {
            get {
                return ResourceManager.GetString("item_season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Похожие товары.
        /// </summary>
        public static string item_similar {
            get {
                return ResourceManager.GetString("item_similar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер.
        /// </summary>
        public static string item_size {
            get {
                return ResourceManager.GetString("item_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип запчасти.
        /// </summary>
        public static string item_sparesType {
            get {
                return ResourceManager.GetString("item_sparesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спецификация.
        /// </summary>
        public static string item_specification {
            get {
                return ResourceManager.GetString("item_specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акция.
        /// </summary>
        public static string item_stock {
            get {
                return ResourceManager.GetString("item_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы экономите.
        /// </summary>
        public static string item_stock_text {
            get {
                return ResourceManager.GetString("item_stock_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочность.
        /// </summary>
        public static string item_strength {
            get {
                return ResourceManager.GetString("item_strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Температура.
        /// </summary>
        public static string item_temperature {
            get {
                return ResourceManager.GetString("item_temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид текстильного изделия.
        /// </summary>
        public static string item_textileProductType {
            get {
                return ResourceManager.GetString("item_textileProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нить.
        /// </summary>
        public static string item_thread {
            get {
                return ResourceManager.GetString("item_thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В корзину.
        /// </summary>
        public static string item_to_cart {
            get {
                return ResourceManager.GetString("item_to_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общий вес.
        /// </summary>
        public static string item_totalWeight {
            get {
                return ResourceManager.GetString("item_totalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип запчасти.
        /// </summary>
        public static string item_type {
            get {
                return ResourceManager.GetString("item_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увеличить.
        /// </summary>
        public static string item_up {
            get {
                return ResourceManager.GetString("item_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гарантийный срок.
        /// </summary>
        public static string item_warrantyPeriod {
            get {
                return ResourceManager.GetString("item_warrantyPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ширина.
        /// </summary>
        public static string item_width {
            get {
                return ResourceManager.GetString("item_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Намотка.
        /// </summary>
        public static string item_winding {
            get {
                return ResourceManager.GetString("item_winding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Синий.
        /// </summary>
        public static string items_blue {
            get {
                return ResourceManager.GetString("items_blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бренд.
        /// </summary>
        public static string items_brand {
            get {
                return ResourceManager.GetString("items_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оформить заказ.
        /// </summary>
        public static string items_checkout {
            get {
                return ResourceManager.GetString("items_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет.
        /// </summary>
        public static string items_color {
            get {
                return ResourceManager.GetString("items_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить покупки.
        /// </summary>
        public static string items_cont_shopping {
            get {
                return ResourceManager.GetString("items_cont_shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string items_price {
            get {
                return ResourceManager.GetString("items_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Красный.
        /// </summary>
        public static string items_red {
            get {
                return ResourceManager.GetString("items_red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товары и услуги.
        /// </summary>
        public static string items_route1 {
            get {
                return ResourceManager.GetString("items_route1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать товары.
        /// </summary>
        public static string items_show {
            get {
                return ResourceManager.GetString("items_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка.
        /// </summary>
        public static string items_sort {
            get {
                return ResourceManager.GetString("items_sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новинки.
        /// </summary>
        public static string items_sort_1 {
            get {
                return ResourceManager.GetString("items_sort_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Популярные.
        /// </summary>
        public static string items_sort_2 {
            get {
                return ResourceManager.GetString("items_sort_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От дорогих к дешевым.
        /// </summary>
        public static string items_sort_3 {
            get {
                return ResourceManager.GetString("items_sort_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От дешевых к дорогим.
        /// </summary>
        public static string items_sort_4 {
            get {
                return ResourceManager.GetString("items_sort_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акция.
        /// </summary>
        public static string items_stock {
            get {
                return ResourceManager.GetString("items_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В корзину.
        /// </summary>
        public static string items_to_cart {
            get {
                return ResourceManager.GetString("items_to_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно добавлен в корзину.
        /// </summary>
        public static string items_to_cart_success {
            get {
                return ResourceManager.GetString("items_to_cart_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код товара.
        /// </summary>
        public static string items_vendoreCode {
            get {
                return ResourceManager.GetString("items_vendoreCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Белый.
        /// </summary>
        public static string items_white {
            get {
                return ResourceManager.GetString("items_white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания ООО &quot;Техно тент&quot; выполняет
        ///полный комплекс работ по изготовлению
        ///автомобильных тентов, крыш, штор из
        ///качественного материала ПВХ с
        ///использованием фурнитуры высокого
        ///качества, возможно нанесение рекламы..
        /// </summary>
        public static string layout_about_company {
            get {
                return ResourceManager.GetString("layout_about_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О компании.
        /// </summary>
        public static string layout_about_company_title {
            get {
                return ResourceManager.GetString("layout_about_company_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Украина, Киев.
        /// </summary>
        public static string layout_address1 {
            get {
                return ResourceManager.GetString("layout_address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ул. Новоконстантиновская, 4 а.
        /// </summary>
        public static string layout_address2 {
            get {
                return ResourceManager.GetString("layout_address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезвонить Вам.
        /// </summary>
        public static string layout_backCall {
            get {
                return ResourceManager.GetString("layout_backCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string layout_backCall_name {
            get {
                return ResourceManager.GetString("layout_backCall_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказать обратный звонок!.
        /// </summary>
        public static string layout_backCall_order {
            get {
                return ResourceManager.GetString("layout_backCall_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезвонить мне.
        /// </summary>
        public static string layout_backCall_submit {
            get {
                return ResourceManager.GetString("layout_backCall_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мобильный телефон.
        /// </summary>
        public static string layout_backCall_tel {
            get {
                return ResourceManager.GetString("layout_backCall_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите мобильный телефон.
        /// </summary>
        public static string layout_backCall_tel_err {
            get {
                return ResourceManager.GetString("layout_backCall_tel_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос или комментарий.
        /// </summary>
        public static string layout_backCall_text {
            get {
                return ResourceManager.GetString("layout_backCall_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пн-Пт: с 09:00 до 18:00.
        /// </summary>
        public static string layout_date1 {
            get {
                return ResourceManager.GetString("layout_date1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сб-Вс - выходной.
        /// </summary>
        public static string layout_date2 {
            get {
                return ResourceManager.GetString("layout_date2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ООО &quot;ТЕХНО ТЕНТ&quot; - Продажа ПВХ тканей, фурнитуры и производство тентовых изделий.
        /// </summary>
        public static string layout_header {
            get {
                return ResourceManager.GetString("layout_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производство.
        /// </summary>
        public static string layout_manuf {
            get {
                return ResourceManager.GetString("layout_manuf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ по телефону.
        /// </summary>
        public static string layout_phone_order {
            get {
                return ResourceManager.GetString("layout_phone_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продажа ПВХ тканей,фурнитуры, производство тентовых изделий от ООО &quot;Техно Тент&quot;.
        /// </summary>
        public static string layout_subtitle {
            get {
                return ResourceManager.GetString("layout_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время работы.
        /// </summary>
        public static string layout_work_time {
            get {
                return ResourceManager.GetString("layout_work_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на войдите в личный кабинет.
        /// </summary>
        public static string login_acc {
            get {
                return ResourceManager.GetString("login_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин или пароль неверный.
        /// </summary>
        public static string login_email_pass_err {
            get {
                return ResourceManager.GetString("login_email_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здравствуйте.
        /// </summary>
        public static string login_hello {
            get {
                return ResourceManager.GetString("login_hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Читать далее.
        /// </summary>
        public static string news_more {
            get {
                return ResourceManager.GetString("news_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новости.
        /// </summary>
        public static string news_title {
            get {
                return ResourceManager.GetString("news_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вытйи.
        /// </summary>
        public static string oders_logout {
            get {
                return ResourceManager.GetString("oders_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История заказов.
        /// </summary>
        public static string oders_title {
            get {
                return ResourceManager.GetString("oders_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ подтверждаю.
        /// </summary>
        public static string order_confirm {
            get {
                return ResourceManager.GetString("order_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать заказ.
        /// </summary>
        public static string order_edit_order {
            get {
                return ResourceManager.GetString("order_edit_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактные данные.
        /// </summary>
        public static string order_form_cont {
            get {
                return ResourceManager.GetString("order_form_cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Способ доставки.
        /// </summary>
        public static string order_form_delivery {
            get {
                return ResourceManager.GetString("order_form_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес доставки.
        /// </summary>
        public static string order_form_delivery_address {
            get {
                return ResourceManager.GetString("order_form_delivery_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город.
        /// </summary>
        public static string order_form_delivery_city {
            get {
                return ResourceManager.GetString("order_form_delivery_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите город.
        /// </summary>
        public static string order_form_delivery_city_choose {
            get {
                return ResourceManager.GetString("order_form_delivery_city_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор способов доставки и оплаты.
        /// </summary>
        public static string order_form_delivery_title {
            get {
                return ResourceManager.GetString("order_form_delivery_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер склада.
        /// </summary>
        public static string order_form_delivery_warehouse {
            get {
                return ResourceManager.GetString("order_form_delivery_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите номер склада.
        /// </summary>
        public static string order_form_delivery_warehouse_choose {
            get {
                return ResourceManager.GetString("order_form_delivery_warehouse_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самовывоз.
        /// </summary>
        public static string order_form_delivery1 {
            get {
                return ResourceManager.GetString("order_form_delivery1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая почта.
        /// </summary>
        public static string order_form_delivery2 {
            get {
                return ResourceManager.GetString("order_form_delivery2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ин Тайм.
        /// </summary>
        public static string order_form_delivery3 {
            get {
                return ResourceManager.GetString("order_form_delivery3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эл. почта.
        /// </summary>
        public static string order_form_email {
            get {
                return ResourceManager.GetString("order_form_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректный адрес электронной почты.
        /// </summary>
        public static string order_form_email_err {
            get {
                return ResourceManager.GetString("order_form_email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш Email.
        /// </summary>
        public static string order_form_email_placeholder {
            get {
                return ResourceManager.GetString("order_form_email_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя и фамилия.
        /// </summary>
        public static string order_form_name {
            get {
                return ResourceManager.GetString("order_form_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя и фамилию.
        /// </summary>
        public static string order_form_name_err {
            get {
                return ResourceManager.GetString("order_form_name_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваше имя и фамилия.
        /// </summary>
        public static string order_form_name_placeholder {
            get {
                return ResourceManager.GetString("order_form_name_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Способ оплатиты.
        /// </summary>
        public static string order_form_payment {
            get {
                return ResourceManager.GetString("order_form_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Безналичный расчет.
        /// </summary>
        public static string order_form_payment1 {
            get {
                return ResourceManager.GetString("order_form_payment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наложенный платеж.
        /// </summary>
        public static string order_form_payment2 {
            get {
                return ResourceManager.GetString("order_form_payment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мобильный телефон.
        /// </summary>
        public static string order_form_tel {
            get {
                return ResourceManager.GetString("order_form_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите мобильный телефон.
        /// </summary>
        public static string order_form_tel_err {
            get {
                return ResourceManager.GetString("order_form_tel_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректный адрес электронной почты.
        /// </summary>
        public static string order_form_tel_err1 {
            get {
                return ResourceManager.GetString("order_form_tel_err1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш телефон.
        /// </summary>
        public static string order_form_tel_placeholder {
            get {
                return ResourceManager.GetString("order_form_tel_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спасибо.
        /// </summary>
        public static string order_success_ty {
            get {
                return ResourceManager.GetString("order_success_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш заказ успешно оформлен. Мы свяжемся с вами в ближайшее время.
        /// </summary>
        public static string order_success_ty_1 {
            get {
                return ResourceManager.GetString("order_success_ty_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оформление заказа.
        /// </summary>
        public static string order_title {
            get {
                return ResourceManager.GetString("order_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К оплате.
        /// </summary>
        public static string order_to_paymnet {
            get {
                return ResourceManager.GetString("order_to_paymnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого.
        /// </summary>
        public static string order_total {
            get {
                return ResourceManager.GetString("order_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мой кабинет.
        /// </summary>
        public static string orders_acc {
            get {
                return ResourceManager.GetString("orders_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Способ доставки.
        /// </summary>
        public static string orders_delivery {
            get {
                return ResourceManager.GetString("orders_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эл. почта.
        /// </summary>
        public static string orders_email {
            get {
                return ResourceManager.GetString("orders_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя и фамилия.
        /// </summary>
        public static string orders_name {
            get {
                return ResourceManager.GetString("orders_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Способ оплаты.
        /// </summary>
        public static string orders_payment {
            get {
                return ResourceManager.GetString("orders_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Личные данные.
        /// </summary>
        public static string orders_private {
            get {
                return ResourceManager.GetString("orders_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string orders_tel {
            get {
                return ResourceManager.GetString("orders_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Читать далее.
        /// </summary>
        public static string partial_articles_more {
            get {
                return ResourceManager.GetString("partial_articles_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная.
        /// </summary>
        public static string partial_cat_menu1 {
            get {
                return ResourceManager.GetString("partial_cat_menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзывы.
        /// </summary>
        public static string partial_cat_menu2 {
            get {
                return ResourceManager.GetString("partial_cat_menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акции.
        /// </summary>
        public static string partial_cat_menu3 {
            get {
                return ResourceManager.GetString("partial_cat_menu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новости.
        /// </summary>
        public static string partial_cat_menu4 {
            get {
                return ResourceManager.GetString("partial_cat_menu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О компании.
        /// </summary>
        public static string partial_cat_menu5 {
            get {
                return ResourceManager.GetString("partial_cat_menu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string partial_cat_menu6 {
            get {
                return ResourceManager.GetString("partial_cat_menu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товары и услуги.
        /// </summary>
        public static string partial_cat_title {
            get {
                return ResourceManager.GetString("partial_cat_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товары.
        /// </summary>
        public static string partial_cat_title1 {
            get {
                return ResourceManager.GetString("partial_cat_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким email уже существует.
        /// </summary>
        public static string registration_email_err {
            get {
                return ResourceManager.GetString("registration_email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не найден.
        /// </summary>
        public static string rest_pass_msg {
            get {
                return ResourceManager.GetString("rest_pass_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите email.
        /// </summary>
        public static string rest_pass_msg_email {
            get {
                return ResourceManager.GetString("rest_pass_msg_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление пароля.
        /// </summary>
        public static string restore_title {
            get {
                return ResourceManager.GetString("restore_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад на.
        /// </summary>
        public static string restorePassMsg_link1 {
            get {
                return ResourceManager.GetString("restorePassMsg_link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на главную страницу.
        /// </summary>
        public static string restorePassMsg_link2 {
            get {
                return ResourceManager.GetString("restorePassMsg_link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мы только что отправили пароль на ваш.
        /// </summary>
        public static string restorePassMsg_msg {
            get {
                return ResourceManager.GetString("restorePassMsg_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите Email.
        /// </summary>
        public static string restorre_email {
            get {
                return ResourceManager.GetString("restorre_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите сообщение.
        /// </summary>
        public static string revew_post_msg {
            get {
                return ResourceManager.GetString("revew_post_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string revew_post_send {
            get {
                return ResourceManager.GetString("revew_post_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что Вам понравилось?.
        /// </summary>
        public static string revew_post_text {
            get {
                return ResourceManager.GetString("revew_post_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Представитель компании &quot;Техно Тент&quot;.
        /// </summary>
        public static string review_author {
            get {
                return ResourceManager.GetString("review_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войдите, чтобы оставить отзыв.
        /// </summary>
        public static string review_autorize {
            get {
                return ResourceManager.GetString("review_autorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анонимный отзыв.
        /// </summary>
        public static string review_post_anonym {
            get {
                return ResourceManager.GetString("review_post_anonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок отзыва.
        /// </summary>
        public static string review_post_title {
            get {
                return ResourceManager.GetString("review_post_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оставить свой отзыв.
        /// </summary>
        public static string review_post_ur_review {
            get {
                return ResourceManager.GetString("review_post_ur_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзывы.
        /// </summary>
        public static string reviews_title {
            get {
                return ResourceManager.GetString("reviews_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Читать далее.
        /// </summary>
        public static string stocks_more {
            get {
                return ResourceManager.GetString("stocks_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акции.
        /// </summary>
        public static string stocks_title {
            get {
                return ResourceManager.GetString("stocks_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на грн.
        /// </summary>
        public static string vallet {
            get {
                return ResourceManager.GetString("vallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на шт.
        /// </summary>
        public static string vallet_item_type {
            get {
                return ResourceManager.GetString("vallet_item_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на грн/м2.
        /// </summary>
        public static string vallet_to_meter {
            get {
                return ResourceManager.GetString("vallet_to_meter", resourceCulture);
            }
        }
    }
}
